# Generated by Django 5.0 on 2023-12-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='slider', verbose_name='Картинка'),
        ),
    ]
