# Generated by Django 5.0 on 2023-12-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_alter_slide_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parthers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pоrtners', verbose_name='фотогравия')),
                ('url', models.URLField(verbose_name='фотография')),
            ],
            options={
                'verbose_name': ('партнер',),
                'verbose_name_plural': 'парнеры',
            },
        ),
    ]
