# Generated by Django 5.0 on 2023-12-23 17:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_remove_parthers_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='kwartal_image/', verbose_name='фото')),
                ('disc', ckeditor.fields.RichTextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': ('Евро квартал',),
                'verbose_name_plural': 'Евро кварталы',
            },
        ),
    ]
