# Generated by Django 5.0 on 2023-12-23 18:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0005_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_image/', verbose_name='фото')),
                ('disc', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': ('Галлерия',),
                'verbose_name_plural': 'Галлерии',
            },
        ),
    ]
