# Generated by Django 5.0 on 2023-12-23 18:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0006_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advan_image/', verbose_name='фото')),
                ('disc_1', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='описание')),
                ('disc_2', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='описание на фото')),
            ],
            options={
                'verbose_name': ('преймушества 1',),
                'verbose_name_plural': 'преймушества 1',
            },
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='disc',
        ),
    ]
