# Generated by Django 5.0 on 2023-12-23 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0007_advantages1_remove_gallery_disc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advantages1',
            old_name='disc_1',
            new_name='disc',
        ),
        migrations.RenameField(
            model_name='advantages1',
            old_name='image',
            new_name='logo',
        ),
        migrations.RemoveField(
            model_name='advantages1',
            name='disc_2',
        ),
    ]
