# Generated by Django 5.0 on 2023-12-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0008_rename_disc_1_advantages1_disc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantages1',
            name='disc',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
