# Generated by Django 5.0 on 2023-12-23 19:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0009_alter_advantages1_disc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantages1',
            name='disc',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
