# Generated by Django 5.0 on 2023-12-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0011_advantages2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advantages2',
            old_name='disc1',
            new_name='disc',
        ),
    ]
