# Generated by Django 5.0 on 2023-12-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0012_rename_disc1_advantages2_disc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantages1',
            name='disc',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='advantages2',
            name='disc',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
