# Generated by Django 5.0 on 2023-12-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='logo_complex',
            field=models.ImageField(upload_to='logo_complex/', verbose_name='Логотип для комплексов'),
        ),
    ]
