# Generated by Django 5.0 on 2023-12-23 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_settings_logo_complex'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='номер телефона')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.settings')),
            ],
        ),
    ]
