# Generated by Django 5.0 on 2023-12-23 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_settingsphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsphone',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_title', to='base.settings'),
        ),
    ]
