# Generated by Django 5.0 on 2023-12-25 18:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='alhtc')),
                ('discriptions', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информационный текст')),
            ],
            options={
                'verbose_name': 'адрес',
                'verbose_name_plural': 'адресы',
            },
        ),
    ]
